### PR TITLE
Add ccls-process-wrapper-function

### PR DESCRIPTION
**Pull request by liff**
To make it possible to run ccls in `nix-shell`. Blatantly stolen almost verbatim from [lsp-haskell](https://github.com/emacs-lsp/lsp-haskell/blob/5c22b80857df32aea5a0d07a9ecb267d62f79fec/lsp-haskell.el#L57).

### CODE REVIEW

**Comment by MaskRay** [comment]
I am not sure why this patch is needed for Nix. Can't you just make up nix-shell command line with `ccls-executable` and `ccls-args`?

**Comment by liff** [comment]
The command needs to refer to `shell.nix` within the project. Given that `ccls-executable` and `-args` are variables, I don’t see how that could be done with them.

**Comment by MaskRay** [comment]
I think you can leverage dynamic binding of `ccls-executable ccls-args`
```elisp
(defun +nix/ccls
  (let ((ccls-executable "nix-shell" ccls-args `("-I" "." "--command" ...))
    (lsp)))
```

**Comment by liff** [comment]
That works, thanks and sorry.

I suppose the reason why `lsp-haskell` has it is that one can just call `(lsp)` directly.

**Comment by MaskRay** [comment]
> I suppose the reason why lsp-haskell has it is that one can just call (lsp) directly.

I've also commented in its PR as I don't think this custom variable is necessary. In any case, the example used isn't good either: the used append/list functions have some redundancy.

You can call `(lsp)` directly if you `(setq ccls-executable .. ccls-args ..)` correctly.

**Pull request closed without merging**
