### PR TITLE
Add function `ccls--get-initialization-options` to provide initializa…

### PR DESCRIPTION
**Pull request by yangyingchao**
…tionOptions.

User can rewrite this function to provide some **project-specific** options.

In my case, I rewrite this function to:

* read project-specific options from `.ccls-root`
* set proper `compilationDatabaseDirectory`

Here is an example:

```
  (defun yc/ccls--get-initialization-options-adv (&rest args)
    "Advice for 'ccls--get-initialization-options'.
Call FUNC which is 'ccls--get-initialization-options with ARGS."
    (let* ((root-dir (locate-dominating-file default-directory ".ccls-root"))
           (root-file (and root-dir (concat root-dir ".ccls-root"))))
      (setq ccls-initialization-options '(:index (:blacklist ("fake_blacklist"))))
      (when root-file
        ;; loading project specific settings from .ccls-root
        (if (and root-file
                 (> (file-attribute-size (file-attributes root-file)) 10))
            (with-temp-buffer
              (insert-file-contents root-file)
              (eval-buffer)
              (message "Loaded project configuration from %s" root-file)))

        ;; guessing compliation database....
        (PDEBUG "Before advice" ccls-initialization-options)
        (unless (member :compilationDatabaseDirectory ccls-initialization-options)
          (catch 'p-found

            (dolist (build '("build" "cmake_build_Debug" "cmake_build_Release"))
              (when (file-exists-p (format "%s/%s/compile_commands.json" root-dir build))
                (push (format "%s/%s/" root-dir build) ccls-initialization-options)
                (push :compilationDatabaseDirectory ccls-initialization-options)
                (throw 'p-found t))))))
      ccls-initialization-options))

  (advice-add 'ccls--get-initialization-options :around
              #'yc/ccls--get-initialization-options-adv)
```

### CODE REVIEW

**Comment by MaskRay** [comment]
I think you may just add a hook to `c++-mode-hook` which does:

```
(setq-local ccls-initialization-options '(...))
(lsp)
```

**Comment by MaskRay** [comment]
I think eglot's def-generic approach is better @yyoncho 

```
(cl-defgeneric eglot-initialization-options (server)
  "JSON object to send under `initializationOptions'"
  (:method (_s) nil)) ; blank default
```

**Comment by yangyingchao** [comment]
yeah, it's an option.
But in this way, my example code will be executed every time when a new file is open in the same project, while it execute only once if an ccls--get-initialization-option function is added.

Am I right?

**Comment by brucestephens** [comment]
I see we can do something similar using `setq-local` in a hook. (Which might be a bit less efficient, depending on how much work is involved to decide what initialization options to use.)

But doesn't this feel at least a bit wrong? There's this variable `ccls-initialization-options` which (in order to use it in `make-lsp-client`) is wrapped in a `lambda`, and now we're changing `ccls-initialization-options` locally.

But if `ccls-initialization-options` (or something similar) were just a function in the first place, the whole thing would be more transparent, wouldn't it? Users would just change that as appropriate.

(Either way it's not a big deal, obviously. I'd guess almost always people don't want any initialization options.)

**Comment by yyoncho** [comment]
> I think eglot's def-generic approach is better @yyoncho

It is more elegant for sure but it is not clear to me what are the benefits at this stage given the fact that  there are so many features of the spec that are not covered. But if you want to change the lsp-mode and then fix all the clients I won't reject the PR.

**Comment by yyoncho** [comment]
@yangyingchao I am not sure whether it will help you but you could use .dir-locals.el to configure lsp as well(it could contain `ccls-initialization-options`)

**Comment by MaskRay** [comment]
Closing in favor of https://github.com/emacs-lsp/lsp-mode/pull/668

**Pull request closed without merging**
